/*
  app.js -- This creates an Express webserver with login/register/logout authentication
*/

// *********************************************************** //
//  Loading packages to support the server
// *********************************************************** //
// First we load in all of the packages we need for the server...
const createError = require("http-errors"); // to handle the server errors
const express = require("express");
const path = require("path");  // to refer to local paths
const cookieParser = require("cookie-parser"); // to handle cookies
const session = require("express-session"); // to handle sessions using cookies
const debug = require("debug")("personalapp:server"); 
const layouts = require("express-ejs-layouts");
const axios = require("axios")

// *********************************************************** //
//  Loading models
// *********************************************************** //
const InterestList = require('./models/InterestList')
const COI = require('./models/COI')

// *********************************************************** //
//  Loading JSON datasets
// *********************************************************** //
const coi = require('./public/data/coi_zipcode.json')

// *********************************************************** //
//  Connecting to the database
// *********************************************************** //
const mongoose = require( 'mongoose' );
const mongodb_URI = 'mongodb+srv://cs103a:mastery@cluster0.ozvn9.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
mongoose.connect( mongodb_URI, { useNewUrlParser: true, useUnifiedTopology: true } );
// fix deprecation warnings
mongoose.set('useFindAndModify', false); 
mongoose.set('useCreateIndex', true);
const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() {console.log("we are connected!!!")});

// *********************************************************** //
// Initializing the Express server 
// This code is run once when the app is started and it creates
// a server that respond to requests by sending responses
// *********************************************************** //
const app = express();
// Here we specify that we will be using EJS as our view engine
app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");

// this allows us to use page layout for the views 
// so we don't have to repeat the headers and footers on every page ...
// the layout is in views/layout.ejs
app.use(layouts);

// Here we process the requests so they are easy to handle
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Here we specify that static files will be in the public folder
app.use(express.static(path.join(__dirname, "public")));

// Here we enable session handling using cookies
app.use(
  session({
    secret: "zzbbyanana789sdfa8f9ds8f90ds87f8d9s789fds", // this ought to be hidden in process.env.SECRET
    resave: false,
    saveUninitialized: false
  })
);

// *********************************************************** //
//  Defining the routes the Express server will respond to
// *********************************************************** //


// here is the code which handles all /login /signin /logout routes
const auth = require('./routes/auth');
const { deflateSync } = require("zlib");
app.use(auth)

// middleware to test is the user is logged in, and if not, send them to the login page
const isLoggedIn = (req,res,next) => {
  if (res.locals.loggedIn) {
    next()
  }
  else res.redirect('/login')
}

// specify that the server should render the views/index.ejs page for the root path
// and the index.ejs code will be wrapped in the views/layouts.ejs code which provides
// the headers and footers for all webpages generated by this app
app.get("/", (req, res, next) => {
  res.render("index");
});

app.get("/about", (req, res, next) => {
  res.render("about");
});


/* ************************
  Loading (or reloading) the data into a collection
   ************************ */
// this route loads in the coi for each zipCode into the COI collection

app.get('/upsertDB',
  async (req,res,next) => {
    for (place of coi){
      const {zip,pop,z_coi_nat,r_coi_nat,stateusps,msaname15,c5_coi_nat}=place;
      await COI.findOneAndUpdate({zip,pop,z_coi_nat,r_coi_nat,stateusps,msaname15,c5_coi_nat},place,{upsert:true})
    }
    const num = await COI.find({}).count();
    res.send("data uploaded: "+num)
  }
)

app.post('/coi/byZip',
  // show coi in a given zip
  async (req,res,next) => {
    const {zipCode} = req.body;
    const coidata = await COI.findOne({zip:zipCode})
    res.locals.coidata = coidata
    res.render('coi')
  }
)

app.get('/coi/show/:zipCode',
  // show all info about a place given its zip
  async (req,res,next) => {
    const {zipCode} = req.params;
    const coidata = await COI.findOne({zip:zipCode})
    res.locals.coidata = coidata
    res.render('coi')
  }
)


app.use(isLoggedIn)

app.get('/addCOI/:zip',
  // add a zipcode to the user's InterestList
  async (req,res,next) => {
    try {
      const zip = req.params.zip
      const userId = res.locals.user._id
      // check to make sure it's not already loaded
      const lookup = await  InterestList.find({zup,userId})
      if (lookup.length==0){
        const InterestList = new  InterestList({zip,userId})
        await InterestList.save()
      }
      res.redirect('/InterestList/show')
    } catch(e){
      next(e)
    }
  })

app.get('/coi/remove/:zip',
  // remove a zipcode from the user's InterestList
  async (req,res,next) => {
    try {
      await  InterestList.remove(
                {userId:res.locals.user._id,
                 zip:req.params.zip})
      res.redirect('/InterestList/show')

    } catch(e){
      next(e)
    }
  }
)

app.get('/InterestList/show',
  // show the current user's InterestList
  async (req,res,next) => {
    try{
      const userId = res.locals.user._id;
      const courseIds = 
         (await  InterestList .find({userId}))
                        .sort(x => x.zipCode)
                        .map(x => x.zip)
      res.locals.courses = await COI.find({zip:{$in: courseIds}})
      res.render('interest')
    } catch(e){
      next(e)
    }
  }
)



// here we catch 404 errors and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// this processes any errors generated by the previous routes
// notice that the function has four parameters which is how Express indicates it is an error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get("env") === "development" ? err : {};
  // render the error page
  res.status(err.status || 500);
  res.render("error");
});


// *********************************************************** //
//  Starting up the server!
// *********************************************************** //
//Here we set the port to use between 1024 and 65535  (2^16-1)
const port = process.env.PORT || "1025";
console.log('connecting on port '+port);
app.set("port", port);

// and now we startup the server listening on that port
const http = require("http");
const server = http.createServer(app);

server.listen(port);

function onListening() {
  var addr = server.address();
  var bind = typeof addr === "string" ? "pipe " + addr : "port " + addr.port;
  debug("Listening on " + bind);
}

function onError(error) {
  if (error.syscall !== "listen") {
    throw error;
  }

  var bind = typeof port === "string" ? "Pipe " + port : "Port " + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case "EACCES":
      console.error(bind + " requires elevated privileges");
      process.exit(1);
      break;
    case "EADDRINUSE":
      console.error(bind + " is already in use");
      process.exit(1);
      break;
    default:
      throw error;
  }
}

server.on("error", onError);
server.on("listening", onListening);
module.exports = app;